name: FrogAnnounce
main: main.java.me.thelunarfrog.FrogAnnounce.FrogAnnounce
authors: [TheLunarFrog]
version: 2.1.0-SNAPSHOT
commands:
    fa:
        description: Get help for FrogAnnounce. Short version of /frogannounce
        usage: /<command>
    frogannounce:
        description: Get help for FrogAnnounce. A shorter version is /fa.
        usage: /<command>
    fa-add:
        description: Add the specified announcement to the list.
        usage: /<command>
permissions:
    frogannounce.*:
        description: Gives full access
        children:
            frogannounce.admin: true
    frogannounce.admin:
        description: Gives full access
        default: op
categories: [INFO, CHAT]
required: []
conflicts: []
optional: []
softdepend: [Vault]