Settings:
    Interval: 5
    Random: false
    Permission: true
    displayMessageOnJoin: false
    showConsoleAnnouncements: false
Announcer:
    Tag: '&DARK_GREEN;[FrogAnnounce] '
    JoinMessage: 'Welcome to the server! Use /help for assistance.'
    #Groups that the plugin should ALWAYS announce to, permitted their world and ignore status allow it.
    GlobalGroups:
        - Moderators
    #Worlds that the plugin should ALWAYS announce to, permitted their group(s) and ignore status allow it.
    GlobalWorlds:
        - world
    Announcements:
        #Announcements are now numbered. Note that the numbers start at 1, and increment by 1.
        #Skipping numbers (i.e. 1, 2, 3, 4, 6) will result in any after the sequence is broken to go unnoticed
        #by the plugin.
        1:
            #Enabled: not necessary. If you wish to disable an announcement so that the plugin will no longer announce it or store it in memory, add this key and set set it to false.
            Enabled: true
            #Text: The text to be announced. Colour codes work as before.
            Text: '&4;Hi.'
            #Specifying an interval makes this announcement independent. If the interval is 1, it will announce once every minute, no matter what.
            #Groups, Worlds, GlobalGroups, and GlobalWorlds filters will still apply. Marking an announcement as independent will not prevent or delay other announcements.
            #For example, if the default config is left as is, it will announce "Hi." four times before saying both "Hi." and "Moo."
            #If you're confused or for more information on this, comment on the FrogAnnounce BukkitDev page.
            Interval: 1
        2:
            Text: '&DARK_GREEN;Moo.'
            #Specific groups.
            #To make it so that ONLY this announcement is seen by certain groups of people, add those groups here.
            #Groups included in GlobalGroups will also receive the announcement.
            Groups:
                - Administrators
                - Donators
        3:
            Text: 'Sooo....'
            #Make it so that the announcement is only seen by people in these worlds. Players in the worlds specified
            #in GlobalWorlds will also receive the announcement.
            Worlds:
                - world_nether
        4:
            #Don't include "" or '' if there isn't a colour code and there's an escape sequence in the string, like so:
            #
            Text: What\'s up?
            Worlds:
                - world_the_end
            Groups:
                - Administrators
                - Donators
        5:
            Text: 'Running a command synchronously with this announcement.'
            #Example of a command.
            #Obviously, you should change it. I don't want 64 stone every 25 minutes if I log into your server. Please.
            #Commands will be run after the text is announced. Obviously, there is no limiting a command's effects to
            #certain groups or worlds, as it is out of a foreign plugin's ability, and must be done by the plugin which that
            #action is performed by.
            #Please be sure that the command can be executed from the console.
            Commands:
                - /give thelunarfrog 1 64
            Worlds:
                - world_the_end
            Groups:
                - Administrators
                - Donators
#Players that the plugin should ignore and NOT announce to, regardless of their group or world. This is changed by the plugin often (/fa ignore and /fa unignore).
#This key does not accept player names as values -- rather, UUIDs; thereby, it is not recommended that users modify this explicitly, in favour of using /fa ignore [player] or /fa unignore [player].
#These commands can, but do not need the [player] argument -- if the argument is supplied, it will apply to another player, rather than the command's invoker. Without, it will reference that same invoker.
ignoredPlayers: []
#Don't change this. This must be present, or the plugin will simply die.
ConfigVersion: 2