Settings:
    Interval: 5
    Random: false
    Permission: true
    displayMessageOnJoin: false
    showConsoleAnnouncements: false
#############################################################################################################
#                                                                                                           #
#                                        ############                                                       #
#                                       #Please READ:#                                                      #
#                                        ############                                                       #
#The announcer's announcements section is a new section, and is configured FAR differently than the old.    #
#                                                                                                           #
#In the end, the change was a necessary evil. I know I will get rage comments about how the configuration   #
#structure is now to complex or something of the sort, but hey -- it was automatically migrated for you, at #
#least!                                                                                                     #
#                                                                                                           #
#With the version this change happened (2.3.0), there comes the ability to restrict all announcements to    #
#certain groups, along with the ability to specify for each announcement -- so, say you want Administrators #
#to get every announcement, you add them to the GlobalGroups list. If you the Donators group to only see    #
#have announcement 2, you'd specify that in announcement 2's groups list.                                   #
#                                                                                                           #
#In addition to the groups change, there's now the ability to restrict announcements to specific worlds.    #
#There's a GlobalWorlds setting for this, too, as well as specific worlds for each announcement, as the     #
#groups system works (see above paragraph).                                                                 #
#                                                                                                           #
#############################################################################################################
Announcer:
    Tag: '&AQUA;[FrogAnnounce]'
    Announcements:
        #Announcements are now numbered. Note that the numbers start at 1, and increment by 1.
        #Skipping numbers (i.e. 1, 2, 3, 4, 6) will result in any after the sequence is broken to go unnoticed
        #by the plugin.
        1:
            #Enabled: not necessary. If you wish to disable an announcement so that the plugin will no longer announce it or store it in memory, add this key and set set it to false.
            Enabled: true
            #Text: The text to be announced. Colour codes work as before.
            Text: '&4;Hi.'
        2:
            Text: '&DARK_GREEN;Moo.'
            #Specific groups.
            #To make it so that ONLY this announcement is seen by certain groups of people, add those groups here.
            #Groups included in GlobalGroups will also receive the announcement.
            Groups:
                - Administrators
                - Donators
        3:
            Text: 'Sooo....'
            #Make it so that the announcement is only seen by people in these worlds. Players in the worlds specified
            #in GlobalWorlds will also receive the announcement.
            Worlds:
                - world_nether
        4:
            #Don't include "" or '' if there isn't a colour code and there's an escape sequence in the string, like so:
            #
            Text: What\'s up?
            Worlds:
                - world_the_end
            Groups:
                - Administrators
                - Donators
        5:
            Text: 'Running a command synchronously with this announcement.'
            #Example of a command.
            #Obviously, you should change it. I don't want 64 stone every 25 minutes if I log into your server. Please.
            #Commands will be run after the text is announced. Obviously, there is no limiting a command's effects to
            #certain groups or worlds, as it is out of a foreign plugin's ability, and must be done by the plugin which that
            #action is performed by.
            #Please be sure that the command can be executed from the console.
            Commands:
                - /give thelunarfrog 1 64
            Worlds:
                - world_the_end
            Groups:
                - Administrators
                - Donators
    #Groups that the plugin should ALWAYS announce to, permitted their world and ignore status allow it.
    GlobalGroups:
        - Moderators
    #Worlds that the plugin should ALWAYS announce to, permitted their group(s) and ignore status allow it.
    GlobalWorlds:
        - world
#Players that the plugin should ignore and NOT announce to, regardless of their group or world. This is changed by the plugin often (/fa ignore and /fa unignore).
ignoredPlayers:
    - TheLunarFrog
#Don't change this. This must be present, or the plugin will simply die.
ConfigVersion: 2