name: FrogAnnounce
main: me.thelunarfrog.frogannounce.FrogAnnounce.FrogAnnounce
authors: [TheLunarFrog]
version: ${project.version}
dev-url: http://dev.bukkit.org/server-mods/frogannounce/
commands:
    fa:
        description: Get help for FrogAnnounce. Short version of /frogannounce
        usage: /<command>
    frogannounce:
        description: Get help for FrogAnnounce. A shorter version is /fa.
        usage: /<command>
permissions:
    frogannounce.*:
        description: Gives full access.
        children:
            frogannounce.admin: true
            frogannounce.optout: true
            frogannounce.optin: true
    frogannounce.admin:
        description: Gives full access.
        default: op
    frogannounce.optout:
        description: Gives access to the /fa optout command.
        default: op
    frogannounce.optin:
        description: Gives access to the /fa optin command.
        default: op
categories: [INFO, CHAT]
required: []
conflicts: []
optional: []
softdepend: [Vault]